name: dair_Vim
root_dir: "/data/DAIR-V2Xset/dataset/cooperative-vehicle-infrastructure/"
train_dir: "/data/DAIR-V2Xset/dataset/cooperative-vehicle-infrastructure/split_datas/train.json"
test_dir: "/data/DAIR-V2Xset/dataset/cooperative-vehicle-infrastructure/split_datas/test.json"
validate_dir: "/data/DAIR-V2Xset/dataset/cooperative-vehicle-infrastructure/split_datas/validate.json"


noise_setting:
  add_noise: False
  args: 
    pos_std: 0.2
    rot_std: 0.2
    pos_mean: 0
    rot_mean: 0

comm_range: 100


yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 2
  epoches: &epoches 60
  eval_freq: 1
  save_freq: 2
  max_cav: &max_cav 2


fusion:
  core_method: 'IntermediateFusionDatasetDAIR' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported

  args:
    proj_first: true
    clip_pc: false
# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32 #32
    max_voxel_train: 32000
    max_voxel_test: 70000
    #grid_size: &grid_size [48,128]
    grid_size: &grid_size [192,512]
  # lidar range for each individual cav. Format: xyzxyz minmax
  cav_lidar_range: &cav_lidar [-102.4, -38.4, -3, 102.4, 38.4, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 4.5
    w: 2
    h: 1.56
    r: [0, 90]

#    bus_l: 11
#    bus_w: 3
#    bus_h: 3.6
#    bus_l: 4.5
#    bus_w: 2
#    bus_h: 1.56
#    bus_r: [0, 90]
    feature_stride: 4
    num: &achor_num 2 #原本是2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.4
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15



# model related
model:
  core_method: point_pillar_Vim_dair
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false
    grid_size: *grid_size
    embed_dim: 256

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64] #64
    point_pillar_scatter:
      num_features: 64

#    base_bev_backbone:
#      layer_nums: [3, 5, 8]
#      layer_strides: [2, 2, 2]
#      num_filters: [64, 128, 256]
#      upsample_strides: [1, 2, 4]
#      num_upsample_filter: [128, 128, 128]

#    shrink_header:
#      kernal_size: [3]
#      stride: [2]
#      padding: [1]
#      dim: [256]
#      input_dim: 384 # 128 * 3
#      # add decoder later

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: AdamW
  lr: 0.001
  args:
    eps: 1e-10
    #weight_decay: 1e-4 #L2正则项，防止过拟合

    weight_decay: 0.3
#lr_scheduler:
#  core_method: step #step, multistep and Exponential support
#  gamma: 0.5****
#  step_size: 10

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [20,40]

#lr_scheduler:
#  core_method: CosineAnnealingWarmRestarts #CosineAnnealingWarmRestarts,step, multistep and Exponential support
#  T_0: 60
#  eta_min: 0.000001
#lr_scheduler:
#  core_method: CosineLRScheduler #CosineLRScheduler,CosineAnnealingWarmRestarts,step, multistep and Exponential support
#  t_initial: *epoches
#  lr_min : 0.000001
#  warmup_lr_init: 0.000001